name: Deploy Supabase Functions

on:
  push:
    branches: [ main ]
    paths:
      - 'supabase/functions/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'supabase/functions/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: 2.20.3

      - name: Deploy Functions
        run: |
          # 変更された関数を検出
          CHANGED_FUNCTIONS=$(git diff --name-only HEAD~1 HEAD | grep '^supabase/functions/' | sed 's/^supabase\/functions\///' | sed 's/\/.*$//' | sort -u || echo "")
          
          if [ -z "$CHANGED_FUNCTIONS" ]; then
            echo "No functions changed"
            exit 0
          fi
          
          # 変更された関数をデプロイ
          for func in $CHANGED_FUNCTIONS; do
            echo "Deploying function: $func"
            supabase functions deploy $func
          done
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }} 