name: Deploy Supabase Functions

on:
  push:
    branches:
      - main
    paths:
      - 'supabase/functions/**'
  pull_request:
    branches:
      - main
    paths:
      - 'supabase/functions/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1

      - name: Deploy Functions
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          # 変更された関数を検出
          CHANGED_FUNCTIONS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^supabase/functions/' | sed 's/^supabase\/functions\///' | sed 's/\/.*$//' | sort -u)
          
          # 変更された関数をデプロイ
          for func in $CHANGED_FUNCTIONS; do
            echo "Deploying function: $func"
            supabase functions deploy $func
          done 