name: Deploy
on:
  push:
    branches:
      - master
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to Test
        if: github.ref == 'refs/heads/master'
        run: |
          npx vercel deploy --token PObfDhj5Ybd3wGTF7yWLsarx --yes --prod --scope yukihamadas-projects --build-env NEXT_PUBLIC_ENV=preview
          npx vercel alias set $(npx vercel ls --token PObfDhj5Ybd3wGTF7yWLsarx --scope yukihamadas-projects -m 1 | grep -m 1 "https://" | awk '{print $2}') test.teai.io --token PObfDhj5Ybd3wGTF7yWLsarx --scope yukihamadas-projects

      - name: Deploy to Production
        if: github.ref == 'refs/heads/release'
        run: |
          npx vercel deploy --token PObfDhj5Ybd3wGTF7yWLsarx --yes --prod --scope yukihamadas-projects --build-env NEXT_PUBLIC_ENV=production