name: Deploy
on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to Test
        if: github.ref == 'refs/heads/main'
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npx vercel deploy --token ${VERCEL_TOKEN} --yes --prod --scope yukihamadas-projects --build-env NEXT_PUBLIC_ENV=preview

      - name: Deploy to Production
        if: github.ref == 'refs/heads/release'
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npx vercel deploy --token ${VERCEL_TOKEN} --yes --prod --scope yukihamadas-projects --build-env NEXT_PUBLIC_ENV=production